Place.create(name: "Test1", address: "Test Address1")
Place.create(name: "Test2", address: "Test Address2")
Place.create(name: "Test3", address: "Test Address3")
Place.create(name: "Test4", address: "Test Address4")
Place.create(name: "Test5", address: "Test Address5")
